name: tip_generator
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - make  # Needed for compilation
  - pathlib
  - pandas
  - litellm
  - python-dotenv
  - pip
  - matplotlib
  - scikit-learn
  - scipy
  - loguru
  - hdbscan
  - sqlalchemy
  - opensearch-py
  - requests
  - fastapi
  - uvicorn
  - pip:
    - unstructured[pdf]
    - sentence-transformers