name: base
channels:
  - conda-forge
dependencies:
  - python=3.11.10
  - pathlib
  - pandas
  - litellm
  - python-dotenv
  - pip
  - scipy
  - loguru
  - hdbscan
  - sqlalchemy
  - requests
  - fastapi
  - uvicorn
  - pip:
    - unstructured[pdf]
    # is required for OpenCV to work properly, needed for unstructured[PDF] parsing
    - opencv-python-headless